spring.application.name=futebol-manager

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/futebol_manager
spring.datasource.username=postgres
spring.datasource.password=admin

# O Hibernate deixa de criar ou alterar tabelas; passa apenas a validar o esquema
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ativar e configurar o Flyway
spring.flyway.repair=true
spring.flyway.repair-on-migrate=true

# Forçar explicitamente o caminho das migrações do Flyway
spring.flyway.locations=classpath:db/migration