spring.application.name=futebol-manager

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/futebol_manager
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true